PrisionersRatio: 0.73
PoliceRatio: 0.27
MinPlayers: 3
MaxPlayers: 11
SecondsInSolitary: 30
DaysAmount: 4
DayDuration: 120
NightDuration: 60
SpeedDuration: 15
SpeedLevel: 2
StartingBalance: 100
TrapLimit: 2
SensorLimit: 2
RadarLimit: -1
EnergyDrinkLimit: -1
CameraLimit: 1
TrapPrice: 10
SensorPrice: 10
RadarPrice: 10
EnergyDrinkPrice: 10
CameraPrice: 10
WaitingPhaseDuration: 300
FullLobbyWaitDuration: 10
FinishedPhaseDuration: 30
DelayBetweenAnnouncements: 30
CommonItemsProbability: 0.8
RareItemsProbability: 0.25
ChestSize: 5
SpeedDuration: 15
SpeedLevel: 2
HelicopterSpawnDelay: 10
HelicopterDepartureDelay: 5
SoundDetectorRange: 2.5
AvailableLanguages:
- "english"
DefaultLanguage: "english"
TeamChatPrefix: "t "
WorldName: "PrisonEscape"
ReferenceBlock:
  X: 0
  Y: 0
  Z: 0
LeavingLocation:
  X: 0
  Y: 0
  Z: 0
WaitingLocation:
  X: 0
  Y: 0
  Z: 0
PrisonTopLeftCornerLocation:
  X: 0
  Y: 0
  Z: 0
PrisonBottomRightCornerLocation:
  X: 0
  Y: 0
  Z: 0
PrisionersSpawnLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
PoliceSpawnLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
SolitaryLocation:
  X: 0
  Y: 0
  Z: 0
SolitaryExitLocation:
  X: 0
  Y: 0
  Z: 0
Helicopter:
  ExitLocation:
    X: 0
    Y: 0
    Z: 0
  JoinLocation:
    X: 0
    Y: 0
    Z: 0
  UpperLocation:
    X: 0
    Y: 0
    Z: 0
  LowerLocation:
    X: 0
    Y: 0
    Z: 0
PrisionersSecretPassagesLocation:
  "1":
    Key:
      X: 0
      Y: 0
      Z: 0
    Value:
      X: 0
      Y: 0
      Z: 0
PoliceSecretPassagesLocation:
  "1":
    Key:
      X: 0
      Y: 0
      Z: 0
    Value:
      X: 0
      Y: 0
      Z: 0
VaultsDirection: "NORTH"
VaultsLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
ChestsLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
GoldenDoorsLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
GrayDoorsLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
CodeDoorsLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
Regions:
  RegionName:
    IsRestricted: false
    "1":
      UpperCorner:
        X: 0
        Y: 0
        Z: 0
      LowerCorner:
        X: 0
        Y: 0
        Z: 0
ChestsContents:
  RegionName:
    Item1Name: 0.25
    Item2Name: 0.05
WallCorners:
  "1":
    X: 0
    Y: 0
    Z: 0
WallCrackFormats:
  "1":
  - "0###0"
  - "#####"
  - "#####"
  - "#####"
  - "0###0"
Maze:
  Format:
  - "E########E"
  - "##########"
  - "##########"
  - "##########"
  - "###SSSS###"
  - "##########"
  - "##########"
  - "##########"
  - "E########E"
  UpperCornerLocation:
    X: 0
    Y: 0
    Z: 0
Fences:
  "1":
    UpperCornerLocation:
      X: 0
      Y: 0
      Z: 0
    LowerCornerLocation:
      X: 0
      Y: 0
      Z: 0
Vents:
  "1":
    X: 0
    Y: 0
    Z: 0
