MaxSimultaneousGames: 4
PrisonersRatio: 0.73
PoliceRatio: 0.27
MinPlayers: 3
MaxPlayers: 11
SecondsInSolitary: 30
DaysAmount: 4
DayDuration: 120
NightDuration: 60
SpeedDuration: 15
SpeedLevel: 2
StartingBalance: 0
TrapLimit: 2
SensorLimit: 2
RadarLimit: -1
EnergyDrinkLimit: -1
CameraLimit: 1
SearchLimit: -1
TrapPrice: 10
SensorPrice: 10
RadarPrice: 10
EnergyDrinkPrice: 10
CameraPrice: 10
SearchPrice: 5
WaitingPhaseDuration: 300
FullLobbyWaitDuration: 10
FinishedPhaseDuration: 30
DelayBetweenAnnouncements: 30
CommonItemsProbability: 0.8
RareItemsProbability: 0.25
ChestSize: 5
SpeedDuration: 15
SpeedLevel: 2
HelicopterSpawnDelay: 10
HelicopterDepartureDelay: 5
SoundDetectorRange: 2.5
RadarDuration: 10
TrapDuration: 10
BlindingDistance: 10
BlindnessSeconds: 5
TradeRequestTimeout: 15
MissionsPerDay: 3
MissionMoneyReward: 10
DifferencesAmount: 3
SequenceSize: 5
SortSize: 5 # must be below 10 and bigger than 2
AvailableLanguages:
- "english"
DefaultLanguage: "english"
TeamChatPrefix: "t "
# Get signature and texture from here: https://mineskin.org/gallery?query=Camera
CameraSkinSignature: "mFtID5cHIjABQMnKzhsy3BEFDDq32QHaJisjaECoLwzhx8dnJxxskA73/Z9DdMBeHlI43+Tdb6bO983K60Pex1f8ncvHFfYMLe1FK44GEpQlkLVnon+iRow5jBxhouicVvSKW578f4k1xo18ml/3gIn78SqJV+2uzVQ23mnFmmUM67JMp7F0i6mwohkNEWaiFdNQGgZbWsL58C0ojzj49ll/ZXGHXc/Jtt4oARGZLaJbICEAzJDQg6BnkquOPpnJUfQ00nk49gyWxo2ID6pI2tSQtGsXv2Apzt1WQxOFnrjVMbWzJYcXRzY2eAZPTGXrkcpms+/CFzk8BRzeSDZ6Q4W98M+3OyIdqoeWQcFFl8Iin5uS95+jBu84wQBr3XLiHw3heePPTX5xLbsGpZEnotXsxSTP6cd30mlPavX+53JXp8nz0ZBCtnkjSPoyVTJ2AJi9uSMPDMJLUU5CbHTUXqH3bhlrZnzrKySynvhn8UhqOnTY1X/13RIadmFajnu6Y3YiaSTPyRCoNdq8oXdhewD9YuzW/OH7A502lRIxoeiZgQLra3o3qBp9+fdFh/cHnc+6rShtr+nzMu17v9Iht+aNIiWZrCYw2eTKQT/EoTnNIL3DA2YuU3KyMZ904nKaeFjGq5TCPY/E8RZjBeJ25Hlbu+sZXJoD4Fl4lW559bo="
CameraSkinTexture: "ewogICJ0aW1lc3RhbXAiIDogMTYwMjg4NDU0Mjg3MCwKICAicHJvZmlsZUlkIiA6ICIyMWUzNjdkNzI1Y2Y0ZTNiYjI2OTJjNGEzMDBhNGRlYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJHZXlzZXJNQyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85OTZhN2I4NjI3Nzg4NzU3MGI5ODI5NzM3NDAzNmE5ZjQ5ZmZjMzBjNmMxYTlmNTFhYWU5NDcyOWU5M2Y5N2FkIgogICAgfQogIH0KfQ=="
WorldName: "PrisonEscape"
PackageItemProbabilities:
  Bolts: 0.3
  DuctTape: 0.01
LeavingLocation:
  World: PrisonEscapeLobby
  X: 0
  Y: 0
  Z: 0
WaitingLocation:
  X: 0
  Y: 0
  Z: 0
PrisonTopLeftCornerLocation:
  X: 0
  Y: 0
  Z: 0
PrisonBottomRightCornerLocation:
  X: 0
  Y: 0
  Z: 0
PrisonersSpawnLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
PoliceSpawnLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
SolitaryLocation:
  X: 0
  Y: 0
  Z: 0
SolitaryExitLocation:
  X: 0
  Y: 0
  Z: 0
Helicopter:
  ExitLocation:
    X: 0
    Y: 0
    Z: 0
  JoinLocation:
    X: 0
    Y: 0
    Z: 0
  UpperLocation:
    X: 0
    Y: 0
    Z: 0
  LowerLocation:
    X: 0
    Y: 0
    Z: 0
AfterEscapeLocation:
  X: 0
  Y: 0
  Z: 0
PrisonersSecretPassagesLocation:
  "1":
    Key:
      X: 0
      Y: 0
      Z: 0
    Value:
      X: 0
      Y: 0
      Z: 0
PoliceSecretPassagesLocation:
  "1":
    Key:
      X: 0
      Y: 0
      Z: 0
    Value:
      X: 0
      Y: 0
      Z: 0
VaultsDirection: "NORTH"
VaultsLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
ChestsLocations:
  "1":
    "1":
      X: 0
      Y: 0
      Z: 0
GoldenDoorsLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
GrayDoorsLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
CodeDoorsLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
CellDoorsLocations:
  "1":
    X: 0
    Y: 0
    Z: 0
Regions:
  Cells: # DO NOT CHANGE THIS REGION NAME
    IsRestricted: false
    "1":
      UpperCorner:
        X: 0
        Y: 0
        Z: 0
      LowerCorner:
        X: 0
        Y: 0
        Z: 0  
  RegionName:
    IsRestricted: false
    "1":
      UpperCorner:
        X: 0
        Y: 0
        Z: 0
      LowerCorner:
        X: 0
        Y: 0
        Z: 0
MissionsRegions:
- "RegionName1"
- "RegionName2"
ChestsContents:
  RegionName:
    Item1Name: 0.25
    Item2Name: 0.05
WallCorners:
  "1":
    X: 0
    Y: 0
    Z: 0
WallCrackFormats:
  "1":
  - "0###0"
  - "#####"
  - "#####"
  - "#####"
  - "0###0"
Maze:
  Format:
  - "E########E"
  - "##########"
  - "##########"
  - "##########"
  - "###SSSS###"
  - "##########"
  - "##########"
  - "##########"
  - "E########E"
  UpperCornerLocation:
    X: 0
    Y: 0
    Z: 0
Fences:
  "1":
    UpperCornerLocation:
      X: 0
      Y: 0
      Z: 0
    LowerCornerLocation:
      X: 0
      Y: 0
      Z: 0
Vents:
  "1":
    X: 0
    Y: 0
    Z: 0
MetalDetectors:
  "1":
    UpperCornerLocation:
      X: 0
      Y: 0
      Z: 0
    LowerCornerLocation:
      X: 0
      Y: 0
      Z: 0
